apiVersion: v1
kind: Pod
metadata:
  name: git-web-server
spec:
  volumes:
  - name: html
    emptyDir: {}
  initContainers:
  - name: init-clonegit
    image: mary001/test:git_sync
    command: ['sh','-c','git clone git@github.com:mary001/kube-example.git /mnt/']
    volumeMounts:
    - name: html
      mountPath: /mnt
  containers:  
  - name: web-server
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  - name: git-sync
    image: mary001/test:git_sync
    volumeMounts:
    - name: html
      mountPath: /mnt
