apiVersion: batch/v1
kind: Job
metadata:
  name: multiple-batch-job
spec:
  completions: 5
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
         - image: alice123/test:batch
           name: main
